### ISSUE TITLE
[5.2.16] UploadedFile::createFromBase requires instance of UploadedFile, breaks when sending empty array of files

### ISSUE THREAD

**Issue by mattmcdonald-uk** [laravel/framework#12317]
Recent changes to the way form files are handled is causing an issue when using various file functions on a Request (like hasFile).

Consider this super simple form example: http://codepen.io/anon/pen/LGaMJo

When you upload 2 files with that form, $request -> hasFile('files') will return true and $request -> file('files') will return an array of UploadedFile instances.

But if you submit the form without any files, you get an array with a single null value. And when Laravel try to parse that it fails because null is not an instance of UploadedFile.

I'm temporarily working around it by checking if $file === null on line 419 of Request.php - I can submit a PR for that fix if wanted? But you may have wanted to resolve it another way.

This has broken very recently - either 5.2.16 or 5.2.15 (was working correctly in 5.2.14)

**Comment by marcoskubis** [comment]
This was fixed -> https://github.com/laravel/framework/blob/5.2/src/Illuminate/Http/Request.php#L410-L421. 
So, the Laravel's source code in composer repository was updated too?

**Comment by mattmcdonald-uk** [comment]
That part is the problem.

[Here](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Http/Request.php#L419), createFromBase expects the object to be an UploadedFile, but it could be null.

**Comment by stevebauman** [comment]
For anyone experiencing this issue (still experiencing it in `v5.2.19`), just verify that you have any files by counting them manually:

```php
// Check if we have any files to upload and attach.
if (count($this->request->allFiles()) > 0) {
    foreach ($this->request->file('files') as $file) {
        $this->issue->uploadFile($file);
    }
}
```

**Comment by mattmcdonald-uk** [comment]
@stevebauman Are you using hasFiles to check your files exist first?

This is fixed for me in 5.2.19

**Comment by stevebauman** [comment]
@mattmcdonald-uk No actually, that's probably a better approach. I was just looping through them without checking for their existence since I thought it was always an empty array if the multiple file input was present:

```php
foreach ($request->file('files') as $file) {
    //
}
```
