### ISSUE TITLE
[5.2] Renaming of attribute name via validation.php not working for arrays

### ISSUE THREAD

**Issue by andreasba** [laravel/framework#12548]
Good evening,

when I create an input field with multiple select option like this:
```PHP
{!! Form::select('test_list[]', $test, null, ['id' => 'test_list', 'class' => 'form-control', 'multiple']) !!}
```
and in validator.php do this:
```PHP
'attributes' => [
   'test_list' => 'Test List'
];
```
or this
```PHP
'attributes' => [
   'test_list.*' => 'Test List'
];
```
I receive the following error message when I do a form validation on the field:
```
test list.3 Format ist ungültig.
```
(German saying that the format of the third entry - which actually is the fourth, but this is another story - is not valid).

Did I do something wrong or is this a bug?

Thanks
Andreas

**Comment by themsaid** [comment]
@andreasba this was fixed in https://github.com/laravel/framework/pull/12578.

The fix shall be available once v5.2.23 is released.

**Comment by seleznevdev** [comment]
@themsaid, still doesn't work.

```php
'attributes' => [
    'attachments.*' => 'Attachment',
],
```

Getting the `The attachments.0 must be an image` error.

**Comment by themsaid** [comment]
This test works for me:

```php
$trans = $this->getRealTranslator();
$trans->addResource('array', [
    'validation.string' => ':attribute must be a string!',
    'validation.attributes.attachments.*' => 'Attachment',
], 'en', 'messages');
$v = new Validator($trans, ['attachments' => [2, 'Jon']], ['attachments.*' => 'string']);
$this->assertFalse($v->passes());
$v->messages()->setFormat(':message');
$this->assertEquals('Attachment must be a string!', $v->messages()->first('attachments.0'));
```
