### ISSUE TITLE
PostgresGrammar@compileColumnExists does not take the connection's schema into account and can return incorrect results.

### ISSUE THREAD

**Issue by davechez** [laravel/framework#13862]
The current code is:

```
public function compileColumnExists($table)
{
     return "select column_name from information_schema.columns where table_name = '$table'";
}
```

The issue is that this function does not take into account the connection's schema so Schema::hasColumn($table, $column) can return incorrect results. 

A quick explanation:

Tables:
schema_1.table_name: column_1, column_2
schema_2.table_name: column_1

Connections:
connection_1 -> schema_1
connection_2 -> schema_2

The following call will return an incorrect result:

`
$hasColumn = Schema::connection('connection_2')->hasColumn('table_name','column_2');
`

$hasColumn will have an incorrect value of *true* because compileColumnExists() only checks against the table name when it should check against the table name AND the current connection's schema.

**Comment by GrahamCampbell** [comment]
Is fixed in the latest release.

**Comment by davechez** [comment]
I checked the 5.3 branch and the master branch and the code is still the same, there is no check against the current connection's schema. I'm sure I'm missing something, can you show me where this is addressed?
