### ISSUE TITLE
[5.3] [bug] Calling artisan commands causes infinite recursion

### ISSUE THREAD

**Issue by balping** [laravel/framework#14950]
Steps to reproduce:

Install the development version of laravel by running `composer create-project laravel/laravel test dev-develop`

In `routes/web.php` place this:

```
Route::get('/', function () {
	\Artisan::call('help');
	return 'hello world';
});
```

If you run this in the browser, you'll get 500 Internal Server Error. If you inspect the error log, you find this message: 

`Maximum function nesting level of '256' reached, aborting!`

I tried increasing the maximum nesting level in the config file, but it doesn't help. If you give it a high-enough value, you'll get a segmentation fault, probably due to reaching memory limits.

Please find my attached log file: [debug.txt](https://github.com/laravel/framework/files/431221/debug.txt)

This bug is only present in L5.3, in 5.2 the above code works.

UPDATE

This got into the stable 5.3 release since I reported it yesterday. Seems a rather critical bug to me.

**Comment by balping** [comment]
I investigated a bit the log file and what I found is that this exact block is repeating itself in the call stack:

```
[Tue Aug 23 00:02:53 2016] PHP 235. App\Console\Kernel->commands() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:81
[Tue Aug 23 00:02:53 2016] PHP 236. require() /tmp/tickettest/app/Console/Kernel.php:38
[Tue Aug 23 00:02:53 2016] PHP 237. Illuminate\Support\Facades\Facade::command() /tmp/tickettest/routes/console.php:18
[Tue Aug 23 00:02:53 2016] PHP 238. Illuminate\Support\Facades\Facade::__callStatic() /tmp/tickettest/routes/console.php:18
[Tue Aug 23 00:02:53 2016] PHP 239. Illuminate\Support\Facades\Facade::getFacadeRoot() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:232
[Tue Aug 23 00:02:53 2016] PHP 240. Illuminate\Support\Facades\Facade::resolveFacadeInstance() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:145
[Tue Aug 23 00:02:53 2016] PHP 241. Illuminate\Container\Container->offsetGet() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:176
[Tue Aug 23 00:02:53 2016] PHP 242. Illuminate\Foundation\Application->make() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Container/Container.php:1182
[Tue Aug 23 00:02:53 2016] PHP 243. Illuminate\Container\Container->make() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:699
[Tue Aug 23 00:02:53 2016] PHP 244. Illuminate\Container\Container->build() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
[Tue Aug 23 00:02:53 2016] PHP 245. Illuminate\Container\Container->Illuminate\Container\{closure}() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
[Tue Aug 23 00:02:53 2016] PHP 246. Illuminate\Foundation\Application->make() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Container/Container.php:230
[Tue Aug 23 00:02:53 2016] PHP 247. Illuminate\Container\Container->make() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:699
[Tue Aug 23 00:02:53 2016] PHP 248. Illuminate\Container\Container->build() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
[Tue Aug 23 00:02:53 2016] PHP 249. ReflectionClass->newInstanceArgs() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
[Tue Aug 23 00:02:53 2016] PHP 250. Illuminate\Foundation\Console\Kernel->__construct() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
[Tue Aug 23 00:02:53 2016] PHP 251. Illuminate\Foundation\Application->booted() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:82
[Tue Aug 23 00:02:53 2016] PHP 252. Illuminate\Foundation\Application->fireAppCallbacks() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:785
[Tue Aug 23 00:02:53 2016] PHP 253. call_user_func:{/tmp/tickettest/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:798}() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:798
[Tue Aug 23 00:02:53 2016] PHP 254. Illuminate\Foundation\Console\Kernel->Illuminate\Foundation\Console\{closure}() /tmp/tickettest/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:798
```

**Comment by balping** [comment]
As I can see Laravel 5.3 went to stable, while this bug seems rather critical to me

**Comment by JackaThompson** [comment]
Was about to open an issue for the same thing. 500 error.

Here's a Laracasts thread with issue: https://laracasts.com/discuss/channels/laravel/laravel-53-1

**Comment by yajra** [comment]
+1 Having the same issue.

**Comment by GrahamCampbell** [comment]
Thanks. This should be fixed on v5.3.1. :)

**Comment by balping** [comment]
I tried it and it is fixed now, thank you

**Comment by sa7bi** [comment]
I've the same bug on laravel 5.4.10. For more details, please see [laracast discusion](https://laracasts.com/discuss/channels/laravel/artisan-routelist-generate-a-fatal-error)

**Comment by sotonin** [comment]
I'm still getting this on Laravel 5.4.16 as well using homestead. Almost entirely stock laravel app. I've only replaced the contents of the Route::get('/') route to make a call to a facade and this is triggered.
