### ISSUE TITLE
Pluralize table name

### ISSUE THREAD

**Issue by piotrooo** [laravel/framework#16709]
- Laravel Version: 5.3.8
- PHP Version: 5.6.11
- Database Driver & Version: mysql  Ver 14.14

### Description:
Its looks like a problem with plural word `metadata`. Eloquent tries to pluralize this word as: `metadatas` (my table is named a `metadata`). Models name: `Metadata`

I search something here: http://english.stackexchange.com/questions/180801/is-metadata-considered-plural

And its seems to be bug in the pluralize engine inside Laravel.

**Example:**

```
$plural = str_plural('metadata');
var_dump($plural); // metadatas
```

### Steps To Reproduce:
* create table `metadata`
* create model `Metadata`
* try to call something `Table 'metadatas' doesn't exist (SQL: select * from metadatas)`

**Comment by fernandobandeira** [comment]
This was fixed in 5.3.26, update your laravel version and try again, check:

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/Pluralizer.php#L32

**Comment by piotrooo** [comment]
Its helps with `metadata` name, but in the `engine_metadata` problem still occur.

**Comment by fernandobandeira** [comment]
Its looking for ``` engine_metadatas ``` ? This is a relationship table between ``` engine ``` and ``` metadata ``` or is it just a common table? If it's a relationship table we could do something about it, if it's a common table then you'll have to specify the table name, we can't cover these cases....

**Comment by piotrooo** [comment]
Yeep, its a common table name.

**Comment by dwightwatson** [comment]
You can always set the table name in your model, so that Laravel doesn't try to work it out automatically.

```php
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'metadata';
```

There's probably a way to teach Laravel certain pluralisations that it doesn't know, but I'm not sure of how.

**Comment by piotrooo** [comment]
Of course, now I have set this property. But, all the models <=> tables relations should be generated automatically.

**Comment by piotrooo** [comment]
So, I close this issue. 
Conclusion:
I'm using `protected $table` property to set a table name.
