### ISSUE TITLE
jQuery is not defined after migrating to Laravel 5.4

### ISSUE THREAD

**Issue by DominiqueFERET** [laravel/framework#17634]
- Laravel Version: 5.4.6
- PHP Version: 7.0.13

### Description:
After migrating to Laravel 5.4 => javascript bug => ReferenceError: jQuery is not defined
(With Elixir in 5.3 everything works fine.)
This variable is defined in asset/js/bootstrap.js

in javascript console, i see "$" is correctly defined and a variable name jQuery311052537473254022181 is define...

Seem to be a suffix added ... A bug of wepack config of laravel.mix ???

### Steps To Reproduce:

Make a simple javascript closure like
function()({ 
...
})(jQuery);

then compile assets with command "npm run dev" (same thing with npm run production).

When you try the javascript closure => jQuery is not defined.

**Comment by reinink** [comment]
Thanks @tabirkeland, that did it for me! I'm no JavaScript wizard, could you explain why `$` would be available globally but not `jQuery`, even though they are both being assigned to `window`?

**Comment by rappasoft** [comment]
I also had this same problem and the above fixed.

**Comment by joval-sv** [comment]
I am having the same issue with Framework 5.4.15, but the above fix does not work.

**Comment by nejtr0n** [comment]
Same issue. Fix does not work =(

**Comment by mhulu** [comment]
Same error in my fresh 5.4.21, I fixed it using:
1. delete window.$ = window.jQuery = require('jquery') in bootstrap.js;
2. in webpack.mix.js add 
mix.webpackConfig({
    resolve: {
        alias: {
            jquery: "jquery/src/jquery"
        }
    }
});

**Comment by mailnike** [comment]
This issue is not yet resolved. Not sure why this was closed?

**Comment by gustav1105** [comment]
If this is happening inside a child vue component you can add this to that component script and it will work
window.$ = window.jQuery = require('jquery');

**Comment by Christophvh** [comment]
@mhulu solution solved my issue.

**Comment by shahzadm287** [comment]
@tabirkeland not work for me :(
@mhulu please mention file location ? where we add this code.
No idea about this file location.

**Comment by UniquelySimilar** [comment]
tabirkeland solution did not work for me either.  I researched Laravel Mix a bit, but didn't want to head down that road just yet.

I found the file /public/js/app.js which appears to contain all of the required js, including jquery.
This appears to be built from /resources/assets/js/app.js by Laravel Mix webpack.mix.js:
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');

I noticed that in /resources/views/layouts/app.blade.php the <script> tag
    <script src="{{ asset('js/app.js') }}"></script>
was the last tag in the <body> tag.

I moved this <script> tag to the top of the <body> tag and this seems to have solved the problem.

**Comment by tabirkeland** [comment]
All, Mix has been updated extensively since my solution was posted.  I would suggest going with @mhulu solution by modifying your `webpack.mix.js` and aliasing JQuery.

**Comment by Sam-WWHC** [comment]
Yo all. I've just been playing about with this. My problem disappeared when I stopped trying to extract bootstrap's into the vendor's.js.
I'm no js Supremo, but I'm guessing that's where a lot of people's problems might be coming from, it's an obvious file to want to extract, It still looks like a bug to me, but hopefully that'll help someone track it down a bit more accurately.

**Comment by ggwebdev** [comment]
Yes @Sam-WWHC! When i stopped of try extract the jquery from node_modules path the problem disappeared! Thanks!

**Comment by devcircus** [comment]
You can extract, but you'll need to autoload as well if you're using any scripts that expect it to be available globally. 

https://github.com/JeffreyWay/laravel-mix/blob/master/docs/autoloading.md

Be sure to only call autoload once and include everything you need autoloaded. Subsequent calls to autoload seem to overwrite previous calls.

**Comment by luchaos** [comment]
thanks @devcircus ! after adding `'jQuery'` to the autoload the extraction works as expected again.

after some recompilations the autoload directive randomly suddenly seemed to make a difference. threw some other errors before that - does webpack cache so hard that it needs several recompilations?

the order in which the extractions are defined doesn't matter, right?

```
mix.js('resources/assets/js/app.js', 'public/js')
    .extract([
        'axios',
        'blazy',
        'bootstrap',
        'd3',
        'jquery',
        'js-cookie',
        'laravel-echo',
        'localforage',
        'localforage-startswith',
        'moment',
        'nvd3',
        'responsive-toolkit',
        'socket.io-client',
        'vue',
        'vue-echo',
        'vue-moment',
        'vue-strap',
        'vuedraggable'
    ])
    .autoload({
        jquery: ['$', 'window.jQuery', 'jQuery'],
    });
```

**Comment by vaxilicaihouxian** [comment]
@muhulu
you save my life

**Comment by shahzadthathal** [comment]
Laravel 5.5
@UniquelySimilar  thanks your solution works, it's not good to move js file in the header but it fixed my issue.
The issue is "app.js" loaded at the end of the file and I need some jquery code in register view so I was getting jquery undefined.

I used @mhulu  solution but after changing mentioned files and after refresh the folder not worked maybe I need to rebuild app.js again, I don't know how to rebuild app.js :)

**Comment by UniquelySimilar** [comment]
@shahzadthathal just to clarify, I suggested moving the script tag to the top of the body tag, not into the head tag.
However, opinions of where to place script tags can vary, like many other ideas in the programming world:
https://stackoverflow.com/questions/3531314/should-i-write-script-in-the-body-or-the-head-of-the-html
I'm not interested in starting a discussion or debate, as it is off the subject of this issue.  Whatever works for a specific situation.

**Comment by chriz74x** [comment]
@devcircus still this doesn't work if you need to bind other components to the same variable.
For example this doesn't work anymore: `window.$ = window.jQuery = require('jquery');require('jquery-ui-bundle');` and for the life of me I can't find a solution to make this bundle work again. All I got is "autocomplete is not a function error". The bundle is mixed in app.js still it's not available to the window.

**Comment by skinnyvin** [comment]
Boostrap etc is loaded at the end of the resources/views/layouts/app.blade.php you can place your scripts after this by adding your js that is reliant on jquery to a section in your view:
`@section('footer-js')
YOUR JS HERE
@endsection`

then yield the section in your layout file AFTER the app.js declaration:

`   <script src="{{ asset('js/app.js') }}"></script>
    @yield('footer-js')`

This way you can keep your js in your view and load it after Jquery is made available by app.js.

**Comment by RPJ18** [comment]
I found a solution for me with something similar to what you wrote. @UniquelySimilar but i didn't put the script tag for app/js on top of body, i put it at the end. Whatever works.

**Comment by UniquelySimilar** [comment]
@RPJ18 thanks for the update.  I recently started working with Vue.js and WebPack, and if doing it again would probably try to resolve this issue with Laravel Mix/WebPack rather than moving the script tag, but it worked for me at the time.

**Comment by abhaymaurya** [comment]
I have been experiencing this issue as well and I found myself the cause of the problem was "defer" attribute in script addition of app.js

<script src="{{ asset('js/app.js') }}" defer></script>

this "defer" tag was forcing script to load only after page was loaded. So I simply put the same attribute to the other js file addition as well where I needed jQuery and of course put it below the app.js addition.

This way both script loaded after page has completed loading and as app.js came before, it made jQuery available to my other script.

Maybe helps someone.

**Comment by tuhin-paul** [comment]
None of the above worked for me. I solved this issue by adding the following:

```
mix.webpackConfig(webpack => {
  return {
	        plugins: [
	            new webpack.ProvidePlugin({
	                $: 'jquery',
	                jQuery: 'jquery',
	                jquery: 'jquery',
	               'window.jQuery': 'jquery'
	        })
	    ]
      };
  })
```
`mix.autoload` is supposed to do the same internally but it somehow isn't working as expected for me. This is the only way I could extract Bootstrap without getting `jQuery is not defined` error.

P.S. found this here: [https://stackoverflow.com/questions/49351415/laravel-mix-uncaught-referenceerror-jquery-is-not-defined](https://stackoverflow.com/questions/49351415/laravel-mix-uncaught-referenceerror-jquery-is-not-defined)

**Comment by mohamedhakika** [comment]
I was having the same problem in laravel 5.7, I tried some solution above did not work,
For me adding `type="text/javascript"` solved the problem.
Before `<script src="{{ asset('js/app.js') }}"></script>`  did not work.
Now `<script src="{{ asset('js/app.js') }}" type="text/javascript"></script>` this solved my day, but I don't know why.

**Comment by rameshnavi** [comment]
Faced the same problem. For me, it was defer loading app.js in the header was creating the issue.
Moved to the footer, removed defer, and added inline script below that. It worked :-) 

```
<script src="{{ asset('js/admin.js') }}"></script>
@yield('local_script')
```

**Comment by steve5287** [comment]
I fixed by just removing "defer" from script tag.
My laravel 5.7 installation included <script src="{{ asset('js/app.js') }}" defer></script> <--- this tag, so i removed the defer as i mentioned before by just leaving <script src="{{ asset('js/app.js') }}"></script> like that... It fixed now =)

**Comment by LarBearrr** [comment]
@steve5287 I too was able to solve the `$` reference error by removing `defer` however, I now have an error about Vue not being able to find `#app` 

Did you run into this same issue?

Also, what is the underlying issue here? It seems rather odd that a vanilla Laravel app would have such difficulty using jQuery in a Blade template.

**Comment by steve5287** [comment]
> @steve5287 I too was able to solve the `$` reference error by removing `defer` however, I now have an error about Vue not being able to find `#app`
> 
> Did you run into this same issue?
> 
> **UPDATE:** Just moving things around, and putting `<script src="{{ asset('js/app.js') }}"></script>` at the end of my layout Blade, before the scripts section has solved both issues. Would still like to know how to get this working without modifying the vanilla templates, if possible.
> 
> Also, what is the underlying issue here? It seems rather odd that a vanilla Laravel app would have such difficulty using jQuery in a Blade template.

I also moved the app.js tag at the end of the blade template. Don't know why they put it at the top "head" tag. Still having problems?

**Comment by bhanushalimahesh3** [comment]
@luchaos autoload  worked like charm for me :)

**Comment by omatamix** [comment]
None of these solutions work for me :(

**Comment by ABTanjir** [comment]
Please re-check if you have added `defer` in your app script or not.
If you have used laravel-mix and added jQuery there make sure your app.js dont have a `defer` attribute

**Comment by andymnc** [comment]
using Laravel 8 in Dec 2020, same issue here.
I could solve with @tuhin-paul solution
putting 
`mix.webpackConfig(webpack => {
    return {
        plugins: [
            new webpack.ProvidePlugin({
                $: 'jquery',
                jQuery: 'jquery',
                jquery: 'jquery',
                'window.jQuery': 'jquery'
            })
        ]`
in webpack.mix.js, then npm run watch (or dev).
Also removing "defer" in app.js raw in blade, and moving all of my js after it.

**Comment by Karu272** [comment]
Using Laravel 8, 19-Jan 2021. 
tried all of these methods and nothing seem to work. I added @tuhin-paul code to all 4 of my webpack.mix.js and run 'npm run watch' but the error is still there. 
I have no idea what to do next. [https://ibb.co/ccvjR6n](url)

**Comment by SpiderFelix** [comment]
This could help! 
var ready = (callback) => {
    if (document.readyState != "loading") callback();
    else document.addEventListener("DOMContentLoaded", callback);
}

then use this function like this
ready( () => {
    ( function() {
        'use strict';
    })(jQuery);
});

works perfectly for me
