### ISSUE TITLE
[5.4] possible bug when running queue listener - The "force" option does not exist.

### ISSUE THREAD

**Issue by lxndrjvr** [laravel/framework#17709]
- Laravel Version: 5.4.7
- PHP Version: 7.0.14

### Description:

[Symfony\Component\Console\Exception\InvalidArgumentException]
The "force" option does not exist.

### Steps To Reproduce:

php artisan queue:listen

### Quick Fix:

class ListenCommand extends Command
{
    protected $signature = 'queue:listen
                            {connection? : The name of connection}
                            **_{--force : be with you} <-- ADDED THIS LINE_**
                            {--queue= : The queue to listen on}
                            {--delay=0 : Amount of time to delay failed jobs}
                            {--memory=128 : The memory limit in megabytes}
                            {--sleep=3 : Number of seconds to sleep when no job is available}
                            {--timeout=60 : The number of seconds a child process can run}
                            {--tries=0 : Number of times to attempt a job before logging it failed}';

**Comment by Stolz** [comment]
See https://github.com/laravel/framework/pull/17687

**Comment by lxndrjvr** [comment]
bug persists even if on fresh install with latest release 5.4.7 which includes the fix from:  [https://github.com/laravel/framework/commit/dc3fa7c45a0b025d487001ea51fedde6b3044001](url)

**Comment by Stolz** [comment]
Actually that commit seems to be the problem, not the solution

**Comment by themsaid** [comment]
That was fixed in https://github.com/laravel/framework/pull/17687/files as @Stolz stated.

**Comment by lxndrjvr** [comment]
@themsaid, the issue still persists even with [#17687](https://github.com/laravel/framework/pull/17687/files)

**Comment by themsaid** [comment]
Ah sorry, https://github.com/laravel/framework/pull/17716 should fix that.

Thank you :)

**Comment by lxndrjvr** [comment]
Works fine now. Thanks ;)
