### ISSUE TITLE
Glyphicons and webpack path problem

### ISSUE THREAD

**Issue by sajadghawami** [laravel/framework#18549]
Hey there,

there seems to be a problem with the path of the glyphicons and webpack.

- Laravel Version: 5.4

### Description:

I've added the following line to my `variables.scss`:

```
$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
```

Now, somehow its assumed that my fonts are found at

```
http://localhost:8000/fonts/glyphicons-halflings-regular.eot
```

and not the `/public/index.php/fonts/` path.

Any ideas?

**Comment by ankurk91** [comment]
Report your issue here -
https://github.com/JeffreyWay/laravel-mix/issues

**Comment by sajadghawami** [comment]
Thanks, i updated the current laravel-mix version and it works.

**Comment by aghayeff** [comment]
I have a problem too. My current icon path in `_variables.css`

`$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/"; `

It is generated font path as 

`src: url(/fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.eot?f4769f9bdb7466be65088239c12046d1);`

I use Laravel 5.4 and trying to set icon path to the directory `../fonts`

When I set it, npm gives an error.

**Comment by sajadghawami** [comment]
what version of `laravel-mix` are you using?

i fixed this problem by using `"laravel-mix": "^0.9.2"` in `package.json`

**Comment by valapy** [comment]
Sorry for comment into a closed post, but, I still have this problem, in my package.json I have "laravel-mix": "0.*" so I think I have the latest laravel-mix version, but it have the same problem, the path is not the correct one, what else I can do? I'm using npm run watch for develope, Do I have to config something else? Or it is suppose to work without any config? I'm sorry.

**Comment by sajadghawami** [comment]
don't worry... have you added this to your `_variables.scss`:

```
$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
```

have you deleted your `node_modules` folder before changing the version for `laravel-mix`?

**Comment by valapy** [comment]
Yes, I did everything you said. But it still doesn't work for me.

**Comment by sajadghawami** [comment]
hmmm, please post your `package.json`.
Only the font-path is not working? Is your webapp deployed somewhere so i can take a look?

**Comment by themsaid** [comment]
Please discuss the issue on the right repository https://github.com/JeffreyWay/laravel-mix/issues
