### ISSUE TITLE
[5.4] Breaking change in ControllerDispatcher::resolveMethodDependencies

### ISSUE THREAD

**Issue by sisve** [laravel/framework#18593]
- Laravel Version: 5.4.13
- PHP Version: 7.1.1

### Description:
The commit https://github.com/laravel/framework/commit/544faace7a605ab2dbf91365f4d46502194357f8 changed ControllerDispatcher::resolveMethodDependencies in a breaking way. It previously kept the array keys, and replaced values in-place for method dependencies. It was changed so that it will now build a new array, without keeping the previous keys.

I am using the previous behavior (and the keys) to reorder the array in [Controller::callAction][1] to allow the methods to have another order of parameters than the order of the route segments, provided they have the same name.

### Test To Reproduce:
    use Illuminate\Routing\ControllerDispatcher;
    
    class ControllerDispatcherTest extends \Illuminate\Foundation\Testing\TestCase {
    
        use CreatesApplication;
    
        public function testResolveMethodDependencies() {
            $parameters = array(
                'locale' => 'tlh'
            );
            $target = new ReflectionMethod(self::class, 'testResolveMethodDependencies_Target');
    
            $controllerDispatcher = new ControllerDispatcher($this->app);
            $actual = $controllerDispatcher->resolveMethodDependencies($parameters, $target);
    
            $expected = array(
                'locale' => 'tlh'
            );
    
            $this->assertEquals($expected, $actual);
        }
    
        protected function testResolveMethodDependencies_Target($locale) {
        }
    
    }

#### 5.4.13 result:

	1) ControllerDispatcherTest::testResolveMethodDependencies
	Failed asserting that two arrays are equal.
	--- Expected
	+++ Actual
	@@ @@
	 Array (
	-    'locale' => 'tlh'
	+    0 => 'tlh'
	 )

[1]: https://github.com/laravel/framework/blob/d3c96686c36c0681cb01251c32f2fc3291d49c6b/src/Illuminate/Routing/Controller.php#L53

**Comment by themsaid** [comment]
Fixed in https://github.com/laravel/framework/pull/18604

**Comment by sisve** [comment]
Another test that still fails, this time with a route segment (`/{tool}/{locale}`) that the action doesn't use.

    use Illuminate\Routing\ControllerDispatcher;
    
    class ControllerDispatcherTest extends \Illuminate\Foundation\Testing\TestCase {
    
        use CreatesApplication;
    
        public function testResolveMethodDependencies() {
            $parameters = array(
                'tool' => 'Grabthar\'s hammer',
                'locale' => 'tlh'
            );
            $target = new ReflectionMethod(self::class, 'resolveMethodDependencies_Target');
    
            $controllerDispatcher = new ControllerDispatcher($this->app);
            $actual = $controllerDispatcher->resolveMethodDependencies($parameters, $target);
    
            $expected = array(
                'tool' => 'Grabthar\'s hammer',
                'locale' => 'tlh'
            );
    
            $this->assertEquals($expected, $actual);
        }
    
        protected function resolveMethodDependencies_Target($locale) {
        }
    
    }

This works on 5.4.12 but fails on 5.4.13

	1) ControllerDispatcherTest::testResolveMethodDependencies
	Failed asserting that two arrays are equal.
	--- Expected
	+++ Actual
	@@ @@
	 Array (
	-    'tool' => 'Grabthar's hammer'
	-    'locale' => 'tlh'
	+    'locale' => 'Grabthar's hammer'
	)

**Comment by themsaid** [comment]
Reopening to look more into the other failing test.

**Comment by sisve** [comment]
Here's another thing that broke; type-hinted parameters without default values.

    use Illuminate\Routing\ControllerDispatcher;

    class ControllerDispatcherTest extends \Illuminate\Foundation\Testing\TestCase {

        use CreatesApplication;

        public function testResolveMethodDependencies() {
            $parameters = array();
            $target = new ReflectionMethod(self::class, 'resolveMethodDependencies_Target');

            $controllerDispatcher = new ControllerDispatcher($this->app);
            $actual = $controllerDispatcher->resolveMethodDependencies($parameters, $target);

            $expected = array();

            $this->assertEquals($expected, $actual);
        }

        protected function resolveMethodDependencies_Target(string $test) {
        }

    }

<br>

    1) ControllerDispatcherTest::testResolveMethodDependencies
    ReflectionException: Internal error: Failed to retrieve the default value

    ~/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php:57

**Comment by sisve** [comment]
I've updated by previous test. The parameters did not have to be type-hinted, it was enough for them to not have a default value.

**Comment by sisve** [comment]
I'm closing this issue since Laravel 5.4.18 has been released with the changes needed.
