### ISSUE TITLE
Model::increment/Model::decrement does not fire Model Events

### ISSUE THREAD

**Issue by Helfull** [laravel/framework#18802]
- Laravel Version: 5.3
- PHP Version: 7.1.1
- Database Driver & Version:

### Description:
Is there any specific reason why `Model::increment`/`Model::decrement` does not fire update events?

### Steps To Reproduce:
Just increment/decrement anything on a model and try to catch `eloquent.updating:*`/`eloquent.updated:*`

**Comment by themsaid** [comment]
Please upgrade to 5.4 since we fixed a lot of the issues that was reported in 5.3

**Comment by Helfull** [comment]
Sorry to say but its not fixed there, but i am not sure if it is bug or intended

**Comment by pankitgami** [comment]
@themsaid , I also confirm this issue. Increment and Decrement function is not firing an event.

**Comment by pankitgami** [comment]
@themsaid I debugged this, If I listen through `DB::listen()`, It is giving me query of increment and decrement. But If I listen through `Event::listen('eloquent.*')` It is not giving me anything.

**Comment by lagbox** [comment]
Im pretty sure it has never fired an event as it doesn't call `save`, it calls `increment/decrement` directly on a builder.

**Comment by FatBoyXPC** [comment]
Why was this issue closed? This issue still exists.

**Comment by deliaahm** [comment]
Anyone can help me?
I have this view post function 
![errorpost](https://user-images.githubusercontent.com/38059468/38978788-8e8f0a4a-43e2-11e8-9c59-6f96d029501a.JPG)

I also make categories for posts  : 
![errorcat](https://user-images.githubusercontent.com/38059468/38978817-a06bcdf2-43e2-11e8-9350-b424d669b087.JPG)

visit count will increase if we view posts.
If i view posts at homepage i don't get error. But if  i try to view posts by categories and get this errror :  
![incr](https://user-images.githubusercontent.com/38059468/38978842-bb7561f8-43e2-11e8-8e43-17cb8585fe81.JPG)

**Comment by TamkeenLMS** [comment]
I think you need to "save" the model after making changes, and then the event will be fired.

Instead of $post->increment(); try 

`$post->update([
'views' => DB::row('views + 1')
])`

I think anyway, not sure :)

**Comment by arthurlauck** [comment]
I think, decrement and increment, should fire update events! It's updating the model.

Please reopen this issue.

**Comment by FatBoyXPC** [comment]
I completely agree here.

**Comment by AurelienMendes** [comment]
Hey ... nothing seems to be moving here.
Can we have an "official" point of view ?
Can we expect such an improvement in the future OR is it not planed at all ?

**Comment by TamkeenLMS** [comment]
+1

**Comment by chrislentz** [comment]
Any updates on this? @themsaid @taylorotwell 

I am curious why an update to a model wouldn't trigger the model update events. I am specifically asking related to Scout. When I increment a comments like count value the comment instance in Algolia is now out of sync.

**Comment by musapinar** [comment]
Hey Googlers,

You may find the official point of view here: https://github.com/laravel/framework/issues/16527#issuecomment-262856444

If you still want to fire an ```updated``` model event, you can change something like this:

```Tag::withTrashed()->whereIn('id', $tagsSynchronization['attached'])->increment('taggables_count', 1);```

into this : 
```Tag::withTrashed()->whereIn('id', $tagsSynchronization['attached'])->get()->each->update(['taggables_count' => \DB::raw('taggables_count + 1')]);```

I just wanted to highlight the fact that, in the context of an increment/decrement, ```getChanges()``` or ```getDirty()``` or ```getAttributes()``` etc, might not return what you'd expect (and need). That is to say, you will have an instance of ```Illuminate\Database\Query\Expression``` (https://laravel.com/api/6.x/Illuminate/Database/Query/Expression.html) --> https://i.imgur.com/cwEzSMq.png

**Comment by bert-w** [comment]
+1

I do want to add though that these `increment` and `decrement` functions have a specific use case, which is to solve concurrency issues when running multiple processes.

Trying to increment or decrement in PHP code using something like:
```
$model->update([
    'value' => $model->value + 1
]);
```
can occasionally cause issues depending on the time the `$model` is retrieved from the database. Since the time of retrieval is not the same as the time of updating, something might've changed in the meantime (like process A wants to change it from 1 to 2, but process B is running at the same time which also retrieved a 1 from the database, incrementing it to 2 (which should be 3)).

In sql (InnoDB) you can ensure that these queries are run one after another (so they are atomic).

**Comment by bert-w** [comment]
After some extra thought I think I know why this is not currently implemented:

If the `updating` hook would be added to the increment/decrement function, you couldnt know the `getDirty()` value of your incrementing column when you retrieve it inside your `updating` callback, since you aren't "setting" the value, but "incrementing".

Since the query doesn't actually become `change col_b to 50`, but instead it will be executed as `change col_b to col_b + 20` (you dont know the end result).

**Comment by amir9480** [comment]
This is my way and it's not perfect but working.

Add this function to your model.

```php
    protected function incrementOrDecrement($column, $amount, $extra, $method)
    {
        $this->{$column} = ($method == 'increment' ? $this->{$column} + $amount : $this->{$column} - $amount);
        $this->fireModelEvent('saving', false);
        $this->{$column} = ($method == 'increment' ? $this->{$column} - $amount : $this->{$column} + $amount);
        $result = parent::incrementOrDecrement($column, $amount, $extra, $method);
        $this->fireModelEvent('saved', false);
        return $result;
    }
```

**Comment by amir9480** [comment]
@themsaid @taylorotwell 
It's 2020 and this issue still exists.

**Comment by bert-w** [comment]
@amir9480 what about updating/updated hooks? Read my last comment to see what the possible issue is.

**Comment by amir9480** [comment]
@bert-w 
First I change attribute on the model.
```php
$this->{$column} = ($method == 'increment' ? $this->{$column} + $amount : $this->{$column} - $amount);
```
Then firing the "saving" event. So i kind of faked dirty.
when the "saving" event done I return them to the original value.

You can also call "updating"/"updated" events.

I know it's not a perfect solution if multiple increments simultaneously happen.

**Comment by vkondratjevs** [comment]
It would be nice to mention this in the documentation ..
blah blah blah .. `increment`/`decrement` do not trigger events `udating`/`updated` .. =|
Spent time after refactoring to understand why observer broke =D
Very very dirty hack .. call the method  `$model->touch();` after...

**Comment by taylorotwell** [comment]
Nobody is thinking this through. There is just complaining.

From my post on another issue:

Note that, sure, we can add the events to this method; **however**, there is no way to gurantee that the dirty / changed values are actually what the values are going to end up being in the database. We must always run this query as a query that looks like `update table set column = column + 1` because multiple processes could be trying to increment the column at the same time.

Therefore, it is impossible for us to know what the new column value will actually be until after we run the query, so the "dirty" value in the `updating` event would always be a guesstimate. It could never be guaranteed to be correct.

**Comment by amir9480** [comment]
@taylorotwell 
Sure using events is not a perfect way.

But is something like this possible to do on Increment/Decrement queries?
```
`table`.`updated_at` = GREATEST(`table`.`updated_at`, :CurrentTime)
```

**Comment by amir9480** [comment]
@taylorotwell

What about just `saved` / `updated`?
Can we get value from the database after updating?
Just `saved` / `updated` gonna fit my need for most cases.
