### ISSUE TITLE
Model:is() and Model:isNot() do not share consistent signature/behaviour, Model:is() doesn't check passed value is valid Model before calling model methods on it.

### ISSUE THREAD

**Issue by SlyDave** [laravel/framework#21131]
- Laravel Version: 5.5

### Description:

Model:is() and Model:isNot() have different signatures/behaviours.

Model:is() accepts nulls, Model:isNot() does not.

Model:is() accepts anything, but if the value is not a null or not a Model, it throw Exceptions because it attempts to call getKey() on the passed value (even if it is not an object)

Model:isNot() throws the expected TypeError because it is type hinted to Model.

#18511 made the change to remove the Model TypeHint from Model:is(), isNot() was added later, but without the same signature. The change also make it so Model:is() started throwing BadMethodCallExceptions rather than TypeError (which it used to do in 5.4)

https://github.com/laravel/framework/pull/21124 provides a functional fix for this, with unit tests, it corrects the exception behaviour to be back to what 5.4 would do (throwing TypeError) and it allows nulls as per the original requirement.

**Comment by SlyDave** [comment]
````
    public function is($model)
    {
        return ! is_null($model) &&
               $this->getKey() === $model->getKey() &&
               $this->getTable() === $model->getTable() &&
               $this->getConnectionName() === $model->getConnectionName();
    }

$model->is(null); // false
$model->is($model); // true
$model->is(fopen('/tmp')); // Exception (but not of TypeError)
$model->is(new StdClass()); // Exception (but not of TypeError)
````

No check is done at all of the $model to see if it is actually a Model

This presents two changes of behaviour of is() from 5.4 to 5.5, one of these changes is documented in the upgrade guide (removal of Model typehint) but the change of Exception throw isn't detailed, and given the usage example in #18511 people might be checking for exceptions thrown...

**Comment by themsaid** [comment]
This is solved in recent commits.

**Comment by SlyDave** [comment]
Taylor's recent commit doesn't resolve this issue, it propagates it to the isNot method, yes it makes the two methods consistent but it doesn't resolve the underlying issue as detailed. it is not type safe, and the exception behavior has changed.
