### ISSUE TITLE
v5.6.29 broke Model Observers

### ISSUE THREAD

**Issue by orkhanahmadov** [laravel/framework#24986]
- Laravel Version: 5.6.29
- PHP Version: 7.2.7
- Database Driver & Version: MySQL

### Description:
Updating Laravel to 5.6.29 breaks Model observers.
Everything works fine on v5.6.28

### Steps To Reproduce:
Create UserObserver for User model.
Create "creating" method inside UserObserver, to assign for example "pin" to user model.
'creating' method won't be called at all on v5.6.29.

**Comment by staudenmeir** [comment]
It works for me. Can you post your code?

**Comment by tillkruss** [comment]
Or ideally a unit test that proves that, so we can avoid breaking it in the future?

**Comment by derekmd** [comment]
If your test suite is failing on Eloquent event assertions, it may be due to a breaking change made to `Event::fake()` called for specific classes:

```php
Event::fake(['eloquent.creating: ' . User::class]);
```

It'll be fixed in 5.6.30 that I assume comes out tomorrow: https://github.com/laravel/framework/pull/24985

**Comment by GrahamCampbell** [comment]
I think this is fixed now, as of the latest release. Please ping if not. :)

**Comment by jameswmcnab** [comment]
@GrahamCampbell This is not fixed yet because v5.6.30 has not yet been released.

I don't know the deciding factors for when a minor release is done but I think that an accidental breaking change should probably be an influential one.

**Comment by RikSomers** [comment]
@GrahamCampbell This is still not fixed at the moment, due to 5.6.30 not being tagged. We use the https://github.com/illuminate/support subtree split for some projects here and the fix missed the 5.6.29 by just a day there.

Any chance a new release could be tagged with the fix? Our test suite is failing at the moment.
