### ISSUE TITLE
[6.x] Flakey memcached tests

### ISSUE THREAD

**Issue by GrahamCampbell** [laravel/framework#29777]
- Laravel Version: 5.8+
- PHP Version: 7
- Database Driver & Version: N/A

### Description:

I see this every few days within the travis builds:

```
There were 2 failures:

1) Illuminate\Tests\Integration\Cache\MemcachedTaggedCacheTest::test_memcached_can_store_and_retrieve_tagged_cache_items

Failed asserting that null matches expected 'foo'.

/home/travis/build/laravel/framework/tests/Integration/Cache/MemcachedTaggedCacheTest.php:19

2) Illuminate\Tests\Integration\Cache\MemcachedTaggedCacheTest::test_memcached_can_store_many_tagged_cache_items

Failed asserting that null matches expected 'foo'.

/home/travis/build/laravel/framework/tests/Integration/Cache/MemcachedTaggedCacheTest.php:41

```

**Comment by driesvints** [comment]
Yeah we need to get that fixed. I've seen that sporadically happen as well.

**Comment by driesvints** [comment]
Going on a limb here and assume this is fixed in Github Actions. If we see it pop back up we can reopen.

**Comment by GrahamCampbell** [comment]
This is still happening, even on GitHub actions. The last build of `master` just failed:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2829600/75161853-62fe0b00-5714-11ea-947c-f7cbf66af425.png">

**Comment by ryangjchandler** [comment]
Is it possible that the TTL of 1 second isn't actually enough sometimes and when the assertion is run, the cache has actually expired?

**Comment by driesvints** [comment]
@ryangjchandler that can indeed be it. Sending in a pr.

**Comment by ryangjchandler** [comment]
> @ryangjchandler that can indeed be it. Sending in a pr.

🤞🏼
