### ISSUE TITLE
[6.x] Console Command Test with table() is broken

### ISSUE THREAD

**Issue by dbpolito** [laravel/framework#31445]
- Laravel Version: 6.x
- PHP Version: 7.3.14 (not relevant)
- Database Driver & Version: (not relevant)

### Description:

With https://github.com/laravel/framework/pull/31426 now any command that uses `table()` is breaking on tests, the reason is at testing we mock a `BufferedOutput` and not a `ConsoleOutput`, which has `section()` method:

https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Testing/PendingCommand.php#L185-L207

I tried to mock `ConsoleOutput` instead but it's not that simple as the output stream at `ConsoleOutput` is done on private methods.

### Steps To Reproduce:

Create a Command that uses `table()` and tests it asserting the exit code.

**Comment by taylorotwell** [comment]
Fixed in 6.15.1.

**Comment by tbuteler** [comment]
Thanks for the quick fix, though I think this error still occurs when the test has the `mockConsoleOutput` property set to `false`.

**Comment by stefanullrich** [comment]
@adam-prickett 
Can confirm, as @tbuteler said, it is not working when testing commands with `mockConsoleOutput`is set to `false` within test. 

```
Call to undefined method Symfony\Component\Console\Output\BufferedOutput::section()
in file /.../vendor/laravel/framework/src/Illuminate/Console/Concerns/InteractsWithIO.php (225)
```

Downgrading to 6.14.0 worked like charm.

**Comment by adam-prickett** [comment]
@tbuteler @stefanullrich I’m going to take a look at this issue this evening and see if I can patch

**Comment by Ghustavh97** [comment]
I side with @stefanullrich. I just upgraded from v6.11.0 => v6.15.1 and `Artisan::output()` broke. No some tests fail.

`Error: Call to undefined method Symfony\Component\Console\Output\BufferedOutput::section()`

**Comment by JosephSilber** [comment]
It also broke my tests, somehow:

https://github.com/JosephSilber/bouncer/runs/443733143?check_suite_focus=true

It fails at this line:

https://github.com/JosephSilber/bouncer/blob/09aa4c45e19a75e0bd9928705f0c95ce234cb622/tests/Concerns/TestsConsoleCommands.php#L49

**Comment by crynobone** [comment]
@JosephSilber

Can you check if the tests breaking on `v6.15.0` and also `v6.15.1`.

I'm not sure how the test would fail on your case since I can't find that the code using `table()`, it might be best to debug if it's related to changes to `PendingCommand` code in `v6.15.1`

**Comment by JosephSilber** [comment]
@crynobone you're right. Bouncer's failing test has nothing to do with this (nor with `PendingCommand`), since it now [also fails on Laravel `6.0.0`](https://github.com/JosephSilber/bouncer/runs/446501770?check_suite_focus=true).

It must be a different dependency that was updated. I'll have to investigate and track that down.

Sorry for adding to the noise here.

**Comment by driesvints** [comment]
We've reverted the entire feature for now because of all the problems popping up.
