### ISSUE TITLE
[7.x] transferStats is undefined for stubbed response via Http::fake()

### ISSUE THREAD

**Issue by Highjhacker** [laravel/framework#31769]
- Laravel Version: 7.0.4
- PHP Version: 7.4.1
- Database Driver & Version: psql 11.5

### Description:
```
1) Tests\Unit\Services\CustomServiceTest::test
Error: Call to a member function getEffectiveUri() on null

/Users/jolanbeer/Development/Sites/mysite/vendor/laravel/framework/src/Illuminate/Http/Client/Response.php:104
/Users/jolanbeer/Development/Sites/mysite/vendor/laravel/framework/src/Illuminate/Http/Client/RequestException.php:24
/Users/jolanbeer/Development/Sites/mysite/vendor/laravel/framework/src/Illuminate/Http/Client/Response.php:187
/Users/jolanbeer/Development/Sites/mysite/app/Services/CustomService.php:302
/Users/jolanbeer/Development/Sites/mysite/app/Services/CustomService.php:262
/Users/jolanbeer/Development/Sites/mysite/app/Services/CustomService.php:77
/Users/jolanbeer/Development/Sites/mysite/tests/Unit/Services/CustomServiceTest.php:70
```
I think it relates somehow to that function :

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Http/Client/PendingRequest.php#L561-L585

The following is not called and so it fails : 

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Http/Client/PendingRequest.php#L480-L482

### Steps To Reproduce:

**In any file, in my case it's a Service :** 

```php
class CustomService
{
    public function my_function()
        try {
            $parameters = ['foo' => 'bar'];
            $response = Http::withToken($this->token())
                ->post('https://api.digitalocean.com/v2/'.ltrim($path, '/'), $parameters);

            $response->throw();

            return json_decode((string) $response->body(), true);
        } catch (RequestException $e) {
            dd($e);
        }
    }
}
```

**Test file :** 

```php
/** @test */
public function test(): void
{
    Http::fake([
        'test.com/*' =>
            Http::response(['foo' => 'bar'], 422, [])
    ]);

    $this->expectException(CustomException::class);
}
```

**Comment by Highjhacker** [comment]
Following snippet solve the issue but there's probably a better way

```php
    public function buildStubHandler()
    {
        return function ($handler) {
            return function ($request, $options) use ($handler) {
                $response = ($this->stubCallbacks ?? collect())
                     ->map(function($stub) use($request, $options){
                         $request = (new Request($request))->withData($options['laravel_data']);
                         $options['on_stats'](new TransferStats($request->request));
                         $response = tap($stub($request, $options), function($response) {
                             $response->transferStats = $this->transferStats;
                         });
                         return $response;
                     })->filter()->first();
                if (is_null($response)) {
                    return $handler($request, $options);
                } elseif (is_array($response)) {
                    return Factory::response($response);
                }
                return $response;
            };
        };
    }
```

**Comment by driesvints** [comment]
We've pushed a fix for this. Will be tagged soon. Thanks for reporting!

**Comment by vgedzius** [comment]
Issue still persists.

- Laravel 7.22.4
- PHP 7.4.5

Code:
```php
class RunStuff
{
    public function run()
    {
        return (string)Http::get(
            'https://jsonplaceholder.typicode.com/posts'
        )->effectiveUri();
    }
}
```

Test code:
```php
class RunStuffTest extends TestCase
{
    public function testExample()
    {
        Http::fake();

        $stuffRunner = new RunStuff();
        $stuff = $stuffRunner->run();

        $this->assertNotEmpty($stuff);
    }
}
```
Test result:
```
1) Tests\Feature\RunStuffTest::testExample
Error: Call to a member function getEffectiveUri() on null

[***]\vendor\laravel\framework\src\Illuminate\Http\Client\Response.php:114
[***]\app\RunStuff.php:13
[***]\tests\Feature\RunStuffTest.php:21

ERRORS!
Tests: 2, Assertions: 1, Errors: 1.
```

Reproducible repo: https://github.com/vgedzius/laravel-http-client-test

**Comment by driesvints** [comment]
@vgedzius that's not how you test with the HTTP client. Please read the docs here: https://laravel.com/docs/7.x/http-client#testing

And try a support channel.

**Comment by vgedzius** [comment]
OK, perhaps I didn't convey my intentions clearly. Here is updated example

```php
class RunStuff
{
    public function run()
    {
        $response = Http::get(
            'https://jsonplaceholder.typicode.com/posts'
        );

        $url = $response->effectiveUri();
        // do something with url, for example logging...

        return $response;
    }
}
```

And the test
```php
public function testExample()
    {
        Http::fake(
            ['jsonplaceholder.typicode.com/*' => Http::response(['test' => 'test'], 200)]
        );

        $stuffRunner = new RunStuff();
        $response = $stuffRunner->run();

        // any assertions
        $this->assertTrue(true);
    }
```

Basically, tests are erroring whenever effectiveUri() call is present in application code.

**Comment by Harti** [comment]
@driesvints I request this to be opened again. 

What @vgedzius presents is a perfectly valid use case in my opinion: Production code could be using effectiveUri (i.e. including all query parameters) for logging or actual logic purposes.

Of course there is the option to use the Http::assertSent() method, but this doesn't magically make the production code vanish (which calls effectiveUri, causing \Error to be thrown).

How exactly do you think the Laravel docs cover this, and why would you say "you're using it wrong" instead of acknowledging this bug?

**Comment by driesvints** [comment]
I'm sorry but I personally don't see how this would work. If you feel that anything can be improved here feel free to PR something 👍

**Comment by Harti** [comment]
Alas, I don't have Git tooling/workflows set up, so all I can do is nag 😄 

https://github.com/laravel/framework/blob/0b989c5c5071e6dc930b22a212d484562ee0bee3/src/Illuminate/Http/Client/Response.php#L120
```
    public function effectiveUri()
    {
        return $this->transferStats->getEffectiveUri();
    }
```
Crashes because `transferStats` is null (when setting `Http::fake()`).

Non-NPE-safe code is generally frowned upon, just make it:
```
    public function effectiveUri()
    {
        return $this->transferStats->getEffectiveUri() ?? null;
    }
```
