### ISSUE TITLE
Eloquent Modal does not Automatically appenging letter "s" in table

### ISSUE THREAD

**Issue by gaspire** [laravel/framework#32769]
- Laravel Version: 7.10.3
- PHP Version: 7.2.28
- Database Driver & Version:

### Description:
Eloquent Modal does not Automatically appenging letter "s" in table

**Comment by patrickbrouwers** [comment]
Can you be more specific? Which table names are failing?

**Comment by fragkp** [comment]
We had the same bug for "Media" Model. It should be fixed after a `composer update`.

Issue: https://github.com/doctrine/inflector/issues/149

**Comment by danielbachhuber** [comment]
I'm experiencing the same issue for a table named `foods`. `composer update` doesn't seem to fix it at this point.

**Comment by danielbachhuber** [comment]
`protected $table = 'foods';` does the trick though. 

It seems like the cause is https://github.com/doctrine/inflector/pull/101, which was only just released.

**Comment by bolduz** [comment]
Same with `work`.

Broken on `doctrine/inflector 1.4.1`, was working fine using `1.3.1`.

[illuminate/support](https://github.com/illuminate/support)'s `composer.json` file was updated to require `"doctrine/inflector": "^1.4|^2.0",`.

It was previously set as `"doctrine/inflector": "^1.1"`. See [this commit](https://github.com/illuminate/support/commit/7ac479470e48bff58400d88dd7b41ee78b69a4d0).

**Comment by gaspire** [comment]
> Can you be more specific? Which table names are failing?

Model name is Homework, table name is homeworks

**Comment by rs-sliske** [comment]
> 
> 
> > Can you be more specific? Which table names are failing?
> 
> Model name is Homework, table name is homeworks

the plural of homework is still homework
