### ISSUE TITLE
route:list command show wrong middleware when using withoutMiddleware function

### ISSUE THREAD

**Issue by malohtie** [laravel/framework#32914]
- Laravel Version: 7.12.0
- PHP Version: 7.4.3
- Database Driver & Version:  : 10.4.11-MariaDB - mariadb.org binary distribution

### Description:
using php artisan route:list command show wrong middleware when using withoutMiddleware function

### Steps To Reproduce:

Routes :
```
 Route::prefix('auth')->middleware('auth:sanctum')->group(function () {
        Route::post('/login', 'AuthController@login')->name('auth.login')->withoutMiddleware('auth:sanctum');
        Route::post('/logout', 'AuthController@logout')->name('auth.logout');
        Route::get('/check', 'AuthController@check')->name('auth.check');
        Route::get('/user', 'AuthController@user')->name('auth.user');
    });
```

![image](https://user-images.githubusercontent.com/20033279/82507920-16e41c00-9af3-11ea-8128-ea5bb334c0a3.png)

**Comment by thisismhp** [comment]
In addition  , if we set middleware in `protected $middlewareGroups` . `api` on `App\Http\Kernel`  its not showing in route middleware list

**Comment by taylorotwell** [comment]
Fixed in next patch release.

**Comment by gargashwani** [comment]
"php": "^7.3|^8.0",
"laravel/framework": "^8.12",
"laravel/sanctum": "^2.8",

Still facing the same issue.

<img width="1229" alt="laravel-sanctum-middleware-issue" src="https://user-images.githubusercontent.com/13774747/103144741-83dc2600-4754-11eb-8145-ab143a869fdc.png">

**Comment by atabixalex** [comment]
> "php": "^7.3|^8.0",
> "laravel/framework": "^8.12",
> "laravel/sanctum": "^2.8",
> 
> Expanded middleware group, How can we remove these.
> 
> <img alt="laravel-sanctum-middleware-issue" width="1229" src="https://user-images.githubusercontent.com/13774747/103144741-83dc2600-4754-11eb-8145-ab143a869fdc.png">

Use option `-c` when calling. Example: `php artisan route:list -c`
