### ISSUE TITLE
`Trying to access array offset on value of type null` when testing artisan commands

### ISSUE THREAD

**Issue by moosapour-arash** [laravel/framework#35870]
- Laravel Version: 7.30.2
- PHP Version: 7.4.13
- Database Driver & Version:

### Description:
after mocking the `Cache` facade, if I call an artisan command, the test immediately crashes with error: `Trying to access array offset on value of type null`. obviously, this error is related to PHP 7.4  and does not happen on older versions of PHP. also I tested on laravel 8 and it works correctly 
### Steps To Reproduce:

- install fresh laravel 7 `composer create-project --prefer-dist "laravel/laravel:^7.0" laravel-7`
- `composer install`
- modify the `ExampleTest` file like this :
```php

   use Illuminate\Support\Facades\Cache;
.
.
.  
    public function testBasicTest()
    {
        Cache::partialMock()->shouldReceive('get')
            ->once()
            ->with('key')
            ->andReturn('value');
        $this->artisan('inspire');
    }
```
- run the test `php vendor/phpunit/phpunit/phpunit --configuration phpunit.xml --test-suffix ExampleTest.php tests/Feature`

**Comment by taylorotwell** [comment]
So the bug doesn't exist on Laravel 8?

**Comment by moosapour-arash** [comment]
@taylorotwell nope, it doesn't. works as expected on Laravel 8

**Comment by taylorotwell** [comment]
OK. As of right now we only make security fixes to Laravel 7. If it is present on Laravel 6 (LTS) we could fix it there.

**Comment by moosapour-arash** [comment]
I just tested on a fresh Laravel 6 and the bug exists there as well

**Comment by driesvints** [comment]
Which exact version of PHPUnit are you using?

**Comment by moosapour-arash** [comment]
@driesvints 
```
            "name": "laravel/framework",
            "version": "v6.20.11",
            "name": "phpunit/phpunit",
            "version": "9.5.0",
```

**Comment by driesvints** [comment]
I'm pretty stumped at this. I have no idea what's affecting the behavior between these two major versions. It does seems to be Laravel specific since I'm testing on the same PHPUnit, PHP and Mockery versions between 6.x and 8.x. Any help is appreciated with figuring this out.

**Comment by driesvints** [comment]
For some reason the required `$app` property on the `CacheManager` isn't set on 6.x even though I verified that the singleton's callback gets called and the app instance is passed correctly. I suspect it has something to do with partial mocking specifically but I cannot figure out why it's different between 6.x and 8.x.

**Comment by crynobone** [comment]
The different between Laravel 6 and 8 is on `App\Providers\RouteServiceProvider` where we now register `RateLimiter` eagerly on every request. This would then resolved `cache.store` before `Cache::partialMock()` occur on the test.

```php
<?php

namespace Illuminate\Tests\Integration\Cache;

use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Foundation\Testing\Concerns\InteractsWithRedis;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\RateLimiter;
use Orchestra\Testbench\TestCase;

/**
 * @group integration
 */
class FacadeTest extends TestCase
{
    public function testBasicTest()
    {
        RateLimiter::for('api', function (Request $request) {
            return Limit::perMinute(60)->by(optional($request->user())->id ?: $request->ip());
        });

        dump($this->app->resolved('cache.store'));

        Cache::partialMock()
            ->shouldReceive('get')
            ->once()
            ->with('key')
            ->andReturn('value');

        $this->artisan('list')->run();
    }

    public function testBasicWithoutRateLimiterTest()
    {
        dump($this->app->resolved('cache.store'));

        Cache::partialMock()
            ->shouldReceive('get')
            ->once()
            ->with('key')
            ->andReturn('value');

        $this->artisan('list')->run();
    }
}
```

![image](https://user-images.githubusercontent.com/172966/104730970-f6e62480-5775-11eb-84b4-4bd8b2b17b03.png)

**Comment by taylorotwell** [comment]
I'm not sure we will be taking any action on this on Laravel 7.x since it is fixed on 8.x.

**Comment by juslintek** [comment]
I still get same error in Feature tests when uri is requested.

It happens here: https://github.com/laravel/framework/blob/8.x/src/Illuminate/Cache/CacheManager.php#L315-L328
> ErrorException : Trying to access array offset on value of type null

Here is my test:
```php
class ShipmentsTest extends TestCase
{
    use RefreshDatabase;
    use GuzzleMock;
    use RoleBasedAccessControlIntegration;

    private string $testDate = '2020-08-09T10:15:00';

    protected function setUp(): void
    {
        parent::setUp();
        Carbon::setTestNow($this->testDate);
    }

    public function testFetchListOfOngoingShipments(): void
    {
        $testNowDate = '2020-11-09T12:24:00';
        Carbon::setTestNow($testNowDate);
        $this->getUser(false, true);

        $this->mockGuzzleDataByService(
            AzureLogicApps::class,
            get_mock_data('Shipments/CMPC_PULP_SPA_ongoing_shipments-2020-11-09-12-24.json')
        );

        Cache::partialMock()->shouldReceive('driver')
            ->once()
            ->with('file')
            ->andReturnNull();

        $response = $this->json('GET', '/api/customer/shipments?status=ongoing');
        $response->assertOk();
        self::assertNotEmpty($response['data']);

        foreach ($response['data'] as $shipment) {
            Assert::assertLessThan($testNowDate, $shipment['load_port_eta']);
            Assert::assertGreaterThan($testNowDate, $shipment['discharge_port_etd']);
        }
    }
}
```
In code I use this check:
```php
...
        $shipments = Cache::driver('file')->get($shipmentsCacheKey);
        if ($shipments !== null && count($shipments) > 0) {
...
```

**Comment by TasneemWahdan** [comment]
I am getting the same error when I run 
php artisan test 
to run all tests
but when I run each test like this it is passed: 
php artisan test --filter createEventByOrganizerTest::test_organizer_can_create_event_with_ticket

I am using Laravel 10

**Comment by joelatgrayv** [comment]
It seems to still exist in 10. Here is a super simple test to show the usage:

```
public function testExample()
{
    Storage::put('file.txt', 'contents');
   
    Storage::partialMock()
        ->shouldReceive('exists')
        ->once()
        ->andReturn(true);

    Storage::exists('file.txt');
    $path = Storage::path('file.txt');
}
```
