### ISSUE TITLE
Laravel(v10.6.0) with octane(v1.5.2): Class "config" does not exist

### ISSUE THREAD

**Issue by MartinPetricko** [laravel/framework#46688]
### Laravel Version

10.6.0

### PHP Version

8.2.4

### Description

After updating laravel from 10.5.1 to 10.6.0 following error is thrown when application used with laravel/octane.

```
ReflectionException: Class "config" does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:914
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(914): ReflectionClass->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->build()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(933): Illuminate\Container\Container->resolve()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Foundation\Application->resolve()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(918): Illuminate\Container\Container->make()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1456): Illuminate\Foundation\Application->make()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(256): Illuminate\Container\Container->offsetGet()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(68): Illuminate\Session\SessionManager->getDefaultDriver()
#8 /var/www/html/vendor/laravel/octane/src/Listeners/GiveNewApplicationInstanceToDatabaseSessionHandler.php(21): Illuminate\Support\Manager->driver()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): Laravel\Octane\Listeners\GiveNewApplicationInstanceToDatabaseSessionHandler->handle()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#11 /var/www/html/vendor/laravel/octane/src/DispatchesEvents.php(20): Illuminate\Events\Dispatcher->dispatch()
#12 /var/www/html/vendor/laravel/octane/src/ApplicationGateway.php(31): Laravel\Octane\ApplicationGateway->dispatchEvent()
#13 /var/www/html/vendor/laravel/octane/src/Worker.php(92): Laravel\Octane\ApplicationGateway->handle()
#14 /var/www/html/vendor/laravel/octane/bin/swoole-server(120): Laravel\Octane\Worker->handle()
#15 [internal function]: {closure}()
#16 /var/www/html/vendor/laravel/octane/bin/swoole-server(170): Swoole\Server->start()
#17 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not exist. in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:916
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->build()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(933): Illuminate\Container\Container->resolve()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Foundation\Application->resolve()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(918): Illuminate\Container\Container->make()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1456): Illuminate\Foundation\Application->make()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(256): Illuminate\Container\Container->offsetGet()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(68): Illuminate\Session\SessionManager->getDefaultDriver()
#7 /var/www/html/vendor/laravel/octane/src/Listeners/GiveNewApplicationInstanceToDatabaseSessionHandler.php(21): Illuminate\Support\Manager->driver()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): Laravel\Octane\Listeners\GiveNewApplicationInstanceToDatabaseSessionHandler->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#10 /var/www/html/vendor/laravel/octane/src/DispatchesEvents.php(20): Illuminate\Events\Dispatcher->dispatch()
#11 /var/www/html/vendor/laravel/octane/src/ApplicationGateway.php(31): Laravel\Octane\ApplicationGateway->dispatchEvent()
#12 /var/www/html/vendor/laravel/octane/src/Worker.php(92): Laravel\Octane\ApplicationGateway->handle()
#13 /var/www/html/vendor/laravel/octane/bin/swoole-server(120): Laravel\Octane\Worker->handle()
#14 [internal function]: {closure}()
#15 /var/www/html/vendor/laravel/octane/bin/swoole-server(170): Swoole\Server->start()
#16 {main}
```

### Steps To Reproduce

1. Install laravel/framework v10.6.0
2. Install and configure laravel/octane v1.5.2 (with swoole)

**Comment by nunomaduro** [comment]
Fixed in Laravel `v10.6.1` and Octane `v1.5.3`.

**Comment by arlindogarcia** [comment]
I'm on laravel version v10.48.25, octane v2.6.0, php 8.3.16 and livewire v3.5.18 and I'm having the same problem, anything I need to do?

**Comment by balthild** [comment]
Using laravel 12.19, octane 2.12, and php 8.4. Still encountering same problem.

**Comment by balthild** [comment]
Looks like it's caused by https://github.com/laravel/octane/blob/2.x/src/Swoole/Handlers/OnWorkerStart.php#L33

~I'll create an issue there~
Related issue: laravel/octane#1047
