### ISSUE TITLE
league/flysystem-aws-s3-v3 problematic to install because of guzzlehttp/guzzle

### ISSUE THREAD

**Issue by manogi** [laravel/framework#47234]
### Laravel Version

10.12.0

### PHP Version

8.2.3

### Description

Using S3 ist problematic (not impossible, but needs extra steps) in the current version of Laravel. The Laravel 10 docs say you need to run the following to use S3: `composer require league/flysystem-aws-s3-v3 "^3.0"`. But when you do this, composer shows an error (see below). It does work if you then use the `--with-all-dependencies` flag, but since that seems to downgrade guzzlehttp/promises from 2.0 to 1.4.1 I am of course not sure what that does to Laravel – so far I had no issues, but who knows?

```
Problem 1
    - league/flysystem-aws-s3-v3[3.12.1, ..., 3.15.0] require aws/aws-sdk-php ^3.220.0 -> satisfiable by aws/aws-sdk-php[3.220.0, ..., 3.271.2].
    - league/flysystem-aws-s3-v3[3.0.0, ..., 3.10.3] require aws/aws-sdk-php ^3.132.4 -> satisfiable by aws/aws-sdk-php[3.132.4, ..., 3.271.2].
    - aws/aws-sdk-php[3.132.4, ..., 3.173.19] require guzzlehttp/psr7 ^1.4.1 -> found guzzlehttp/psr7[1.4.1, ..., 1.9.1] but the package is fixed to 2.5.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - aws/aws-sdk-php[3.173.20, ..., 3.198.8] require guzzlehttp/psr7 ^1.7.0 -> found guzzlehttp/psr7[1.7.0, ..., 1.9.1] but the package is fixed to 2.5.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - aws/aws-sdk-php[3.199.0, ..., 3.271.2] require guzzlehttp/promises ^1.4.0 -> found guzzlehttp/promises[1.4.0, ..., 1.5.3] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires league/flysystem-aws-s3-v3 ^3.0 -> satisfiable by league/flysystem-aws-s3-v3[3.0.0, ..., 3.15.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

### Steps To Reproduce

Do a fresh install with 
```
laravel new some-new-website
```

try to 
```
composer require league/flysystem-aws-s3-v3 "^3.0" 
```

inside that new website.

**Comment by GrahamCampbell** [comment]
> seems to downgrade guzzlehttp/promises from 2.0 to 1.4.1

That's odd. I would expect it to go to 1.5.3. Can you run `composer why guzzlehttp/promises` from that state you end up in where you have 1.4.1?

**Comment by GrahamCampbell** [comment]
Using v1 of the Guzzle promises library is fine with Laravel FYI, though you would definitely want 1.5.3, and not 1.4.1 as there are some issues in that version and PHP 8.2 non-compatibility, that are fixed in 1.5.3.

**Comment by manogi** [comment]
I am sorry - it does run on version 1.5.2, not 1.4.1

But it is still not quite right that the `composer require league/flysystem-aws-s3-v3 "^3.0" ` copied directly from the docs should not work without the flag, or am I mistaken?

**Comment by manogi** [comment]
(edited - 1.5.3 instead of 1.5.2)

**Comment by GrahamCampbell** [comment]
`--with-all-dependencies` should probably be added to the docs.

**Comment by nunomaduro** [comment]
Fixed: https://github.com/laravel/docs/pull/8821.
