### ISSUE TITLE
Eloquent generics

### ISSUE THREAD

**Issue by rcerljenko** [laravel/framework#54573]
### Laravel Version

11.42.0

### PHP Version

8.4.3

### Description

Hi,

With the latest update we started to receive these errors.

This scope is a part of the trait that any model can use.

```php
public function scopeSearch(Builder $query, ?string $search = null): Builder
{
	return $query->whereHas('user', static function (Builder $query) use ($search): void {
		/**
		 * @var Builder<static> $query
		 */
		$query->search($search);
	});
}
```

```
PHPDoc tag @var with type Illuminate\Database\Eloquent\Builder<static(App\Models\Admin)> is not subtype of native type Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>.
- varTag.nativeType
```

### Steps To Reproduce

Copy this code in a trait and use it on some model.

```php
public function scopeSearch(Builder $query, ?string $search = null): Builder
{
	return $query->whereHas('user', static function (Builder $query) use ($search): void {
		/**
		 * @var Builder<static> $query
		 */
		$query->search($search);
	});
}
```

**Comment by rcerljenko** [comment]
@calebdw you will probably have a good starting point on this

**Comment by rcerljenko** [comment]
i suspect this is the related PR...

https://github.com/laravel/framework/pull/54452

**Comment by calebdw** [comment]
You need the generics on the input parameter:


```
/**
  * @param Builder<static> $query
  * @return Builder<static>
  */
public function scopeSearch(Builder $query, ?string $search = null): Builder
{
	return $query->whereHas('user', static function (Builder $query) use ($search): void {
		$query->search($search);
	});
}

**Comment by rcerljenko** [comment]
Hi,

I did that but now it says this:
```
Call to an undefined method Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>::search().
```

**Comment by calebdw** [comment]
I have a Larastan PR to be able to detect the dynamic generic type: https://github.com/larastan/larastan/pull/2048

It hasn't been merged yet but I've also published it on my fork if you'd like to check it out: https://github.com/calebdw/larastan

**Comment by rcerljenko** [comment]
Hi,

I'll try it out later today and let you know.. thx!

**Comment by rcerljenko** [comment]
HI,

I tried the second approach that you mentioned and I managed to fix most of the problems. However, morph relations are still a problem.

Given the example:

```php
public function item(): MorphTo
{
	return $this->morphTo();
}

public function scopeAvailable(Builder $query): Builder
{
	/**
	 * @var Builder<static> $query
	 */
	return $query->whereHas($query->getModel()->item(), static function (Builder $query): void {
		$query->available();
	});
}
```

`scopeAvailable` also exists on all morphed models via `item` relation. PHPstan returns this:

```
Call to an undefined method Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>::available().
```

It's the same when Builder generic is typed as a function input param.

**Comment by calebdw** [comment]
`MorphTo` is inherently dynamic and there's no way to safely know what model is being returned. If you only have a few models then you could do something like:

```php
/** @return MorphTo<Model1|Model2> */
public function item(): MorphTo
{
    return $this->morphTo();
}
```
however, you will have to manually ignore the warning that is produced by doing so.

You might have better mileage using the `where*Morph*` methods:

```php
return $query->whereHasMorph($query->getModel()->item(), [Model1::class, Model2::class], static function (Builder $query): void {
    $query->available();
});
```
This however, will require the Larastan PR (or my fork) to be able to properly detect the builder type.


This is not a framework issue, but just has to do with properly typing the generics in your code. This issue can be closed but feel free to open discussions at the Larastan repo if you have more questions---I'm happy to help 😃

**Comment by rcerljenko** [comment]
Thanks for the explanation. So you're saying that there's no way to properly type morphs for now?
I mean I could type all possible models as you said but that's not a solution for this.
I want to be able to properly type relations and not to worry about forgotten model typings on morph definitions.
