### ISSUE TITLE
Catching errors when using `Bus::batch` inside of `Bus::chain` on Sync Queue

### ISSUE THREAD

**Issue by justlunix** [laravel/framework#55077]
### Laravel Version

11.44.2

### PHP Version

8.2.27

### Description

When using `Bus::chain(...)->catch(...)`, the catch callback will be transferred to a `Bus::batch` inside of the chain. This will result in the same callback to be executed twice, once for the batch and then for the chain. I do not understand why this should happen. The chain and the batch both have providable catch callbacks, so why would a batch receive all of the chain callbacks on top?

Another thing.

On the sync queue (like in PHPUnit tests), the catch callback of Bus::batch is run in a transaction, which will even reverse any database changes done in the catch callback. That means I have to add checks inside of the catch callback since it's called twice, but I cannot test those check because my phpunit runs through the sync queue, which will revert any database changes in the first callback.

For reference:

- Batches are run inside of transaction, which will revert the changes on sync queue: vendor/laravel/framework/src/Illuminate/Bus/Batch.php:187
- Chain catch callbacks are added to batch, which will make the callback execute twice: vendor/laravel/framework/src/Illuminate/Bus/ChainedBatch.php:100

### Steps To Reproduce

```php
Bus::chain(
    Bus::batch([....]),
    Bus::batch([....]),
    Bus::batch([....]),
)->catch(static fn() => logger()->info('hi'))->dispatch();
```

1. Create a job chain like the above and make sure the job inside the batch fails.
2. Configure to use the sync queue, i.e. through calling the code within a phpunit test.
3. Run the code, check the logs.

For reference:

- Batches are run inside of transaction, which will revert the changes on sync queue: vendor/laravel/framework/src/Illuminate/Bus/Batch.php:187
- Chain catch callbacks are added to batch, which will make the callback execute twice: vendor/laravel/framework/src/Illuminate/Bus/ChainedBatch.php:100

**Comment by bernardwiesner** [comment]
I am not sure if its the same issue, but I once attempted to submit a PR for something similar: https://github.com/laravel/framework/pull/48704

**Comment by crynobone** [comment]
Should be fixed via [#57322](https://github.com/laravel/framework/pull/57322)

**Comment by justlunix** [comment]
@crynobone The same issue still exists in version 12. Will it be fixed there as well?
