### ISSUE TITLE
Parse multiple repeated request parameters. Use Request::Input to return the array

### ISSUE THREAD

**Issue by mmichaelbiz** [laravel/framework#8434]
Ability to handle repeated request params with the same key. Example: 

GET https://www.myapi.com/api/v1/entity?q=param1&q=param2

(Note that there are two 'q' params)

Perhaps using Request::input('q') to return an array in this case with the multiple repeated values. Currently it returns only the last value (i.e. param2).

I know we can handle multiple values on a single param with a comma separator for example: GET https://www.myapi.com/api/v1/entity?q=param1,param2

Could be nice to also handle repeat multiple params as it seems that there are others following this convention. Below is a real world example from the google translate api using repeat params:

GET https://www.googleapis.com/language/translate/v2?key=INSERT-YOUR-KEY&source=en&target=de&q=Hello%20world&q=My%20name%20is%20Jeff

Note also original question raised as a post on Laracasts: 
https://laracasts.com/discuss/channels/general-discussion/how-can-we-parse-multiple-url-params-with-the-same-value-in-laravel

**Comment by GrahamCampbell** [comment]
Repeated parameters make no sense and should be avoided without exception.

**Comment by mmichaelbiz** [comment]
That's a shame. Seems to make sense for the guys at google...

**Comment by franzliedke** [comment]
Just to clarify: @GrahamCampbell: Were you referring to the first example URL with two equally-named parameters (that should indeed not be possible) or the other examples, e.g. with comma-separated values?

Because we could easily add a simple helper method like `Request::multiple('q')' which would easily parse these parameters when requested to do so (which avoids doing this kind of stuff automatically - bad magic -, but still makes it possible).

**Comment by mmichaelbiz** [comment]
@franzliedke, to be honest I was looking to use the best convention for handling repeat url params. I did not know what that was so I did a little research on how the major players worked their APIs and came across the first example URL I referred to as used by google during my research.

Adding something like Request::multiple('q') to parse delimited separated params could be a great way to handle this. Perhaps using comma by default, or you could even specify the delimiter as an additional argument for some extra versatility?

**Comment by franzliedke** [comment]
Yep, exactly what I was thinking...

**Comment by mmichaelbiz** [comment]
Awesome, I hope it gets the rubber stamp :+1: 

Just to help me understand, what are the concerns about repeating the param in URL?

To give you a simple example use case I had in mind, I was thinking to use this as a lazy way to build up a search URL. e.g. I have a bunch of articles that have various searchable params, tags, categories etc.

On the front end the user would select the search params, tags, categories etc and for each one selected I would just append the relevant param ending up with something like GET https://www.myapi.com/api/v1/entity?q=Red&cat=Food&cat=Health&cat=Food&q=Blue&q=Green.

Laravel as my API would then just grab all the 'q's and all the 'cat's, get the filtered data and return the filtered response.

**Comment by bbashy** [comment]
If I built an API that required that, I'd use an array.

q[0]=1&q[1]=2&q[2]=3 - already indexed and
q=1&q=2&q=3 = hard to debug and PHP doesn't read them as standard (https://php.net/parse_str)

**Comment by mmichaelbiz** [comment]
Thanks @bbashy. 

That could be a great way to pass through your own keys if you needed to. Perhaps the helper function could accept these also.

It does make building the URL a little more complicated however and not really needed for the use case I had in mind so would be good to be able to build the url in the 'lazy' way without the indexes.

I've also replied to your good example on the Laracasts thread. Thanks again for the examples on both!

**Comment by franzliedke** [comment]
@taylorotwell Any opinion on a PR for `Input::multiple()` that parses a query string parameter value like `val1,val2,val3` to an array? (It could take an additional parameter with the separator, obviously.)

**Comment by taylorotwell** [comment]
I think it's a decent idea. It seems like it should be handled by Request::query though.

**Comment by lukasgeiter** [comment]
@taylorotwell You mean `query($key = null, $default = null, $delimiter)`?
I don't really like it, as the default value kind of gets in the way. I'd prefer a new method for this.

**Comment by mmichaelbiz** [comment]
@taylorotwell / @GrahamCampbell could we open this issue back up again?

**Comment by mmichaelbiz** [comment]
:+1:

**Comment by FractalizeR** [comment]
Commited initial implementation using backwards-compatible change of existing methods.

**Comment by Ilyes512** [comment]
I also implemented this using a helper function. Only difference is that I use $request->query->get() and $request->query->all(). I did this cause I saw a warning in the symfony component that using the all() was slower. Not sure if it's that much slower. So I am referring to this line that would be slower then using the query directly: https://github.com/FractalizeR-Forks/laravel-framework/blob/294be2611c984deb0faa619418d5c62334a6b31f/src/Illuminate/Http/Request.php#L286

Not sure if this is a "valid/good" reason to use query directly?

**Comment by coatesap** [comment]
@GrahamCampbell - can we open this issue back up, as it seems the discussion and linked PR got sidetracked onto dealing with delimiter-separated values. The original issue still remains that there isn't a reliable way to receive an array from a query string with repeated parameters names in Laravel. 

I'm aware that this is caused by the underlying limitation of PHP's `parse_str()` function. Of course, it's possible to do your own parsing, but it's not especially simple. It seems the Drupal contributors have had [an attempt to do the same thing](https://www.drupal.org/project/drupal/issues/3038774). It would be great if Laravel could provide a well-tested method out of the box.

The real-world use case that I've come up against recently is when generating SDKs for a Laravel-based API. Currently the OpenAPI standard only supports [certain methods of serialisation for query string parameters](https://swagger.io/docs/specification/serialization/#query) of which the repeated parameter is probably the most robust for passing arrays of strings.

**Comment by brunogonncalves** [comment]
> Repeated parameters make no sense and should be avoided without exception.

Repeated parameters are normal, and the "fetch" method of javascript, by default repeat parameters in URL if the param is an array, is very common and I've worked as a frontend in many projects and the backend guys working perfectly with there's repeated parameters in url.

**Comment by elhaouari-mohammed** [comment]
@GrahamCampbell 

Here is a scenario where the brackets would fail : 

let's say I have the following link for a search page : 

```
https://example.com/search?amenities[]=air-conditioning&amenities[]=pool-table
```

wich will be parsed on the backend like this :

```json
{
  "amenities": [
    "air-conditioning",
    "pool-table"
  ]
}
```

Let's copy this link and share it on Facebook or send it inside a message, Facebook then will encode it to ASCII. Click afterward on that link and it becomes like this : 

```
https://example.com/search?amenities[0]=air-conditioning&amenities[0]=pool-table
```

wich will be parsed on the backend like this :

```JSON
{
  "amenities": [
    "pool-table"
  ]
}
```

this a scenario that we are currently facing on a production app, all of our links shared through Facebook are not working because of this.

**Comment by nilsgabriel** [comment]
Maybe there is a better solution, but my helper function currently looks like this:

`<?php

if ( !function_exists('query')  )
{
	function query ($key = null) {

		$url = parse_url(request()->getRequestUri());
		$query  = explode('&', $url['query']);
		$params = array();

		foreach($query as $param)
		{
			list($name, $value) = explode('=', $param);
			$params[urldecode($name)][] = urldecode($value);
		}

		if(array_key_exists($key, $params)) return $params[$key];
		if($key) return null;
		return $params;
	}
}
`

**Comment by jawwadkalia** [comment]
This functionality was added back then?
