### ISSUE TITLE
[L5.2][php7] Error with exeption 

### ISSUE THREAD

**Issue by Codenator81** [laravel/framework#9650]
This error came when I try use Mail fasade in controller
FatalErrorException in FlattenException.php line 76:
Uncaught TypeError: Argument 1 passed to Symfony\Component\Debug\Exception\FlattenException::create() must be an instance of Exception, instance of TypeError given, called in /home/alex/www/laravel.local/vendor/symfony/debug/ExceptionHandler.php on line 206 and defined in /home/alex/www/laravel.local/vendor/symfony/debug/Exception/FlattenException.php:76
Stack trace:
#0 /home/alex/www/laravel.local/vendor/symfony/debug/ExceptionHandler.php(206): Symfony\Component\Debug\Exception\FlattenException::create(Object(TypeError))
#1 /home/alex/www/laravel.local/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(93): Symfony\Component\Debug\ExceptionHandler->createResponse(Object(TypeError))
#2 /home/alex/www/laravel.local/app/Exceptions/Handler.php(42): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(TypeError))
#3 /home/alex/www/laravel.local/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(101): App\Exceptions\Handler->

As you can see not useful info what sup )

I using Laravel 5.2.x-dev

**Comment by GrahamCampbell** [comment]
Laravel 5.2 isn't supported at all yet. Sorry.

**Comment by GrahamCampbell** [comment]
Symfony will be fixing this in due course, but it may take until November.

**Comment by GrahamCampbell** [comment]
I'm actually going to keep this open so I can personally keep track of this, since this will become important in the future if not addressed before we launch 5.2. Thank you very much for reporting @Codenator81. :)

**Comment by Codenator81** [comment]
Lol I am stupid this is Symfony issue))) I think there issue all ready )

**Comment by GrahamCampbell** [comment]
Is there any chance you could paste a link here. It will be useful for anyone else testing out new stuff early, and indeed for me to check out. :)

**Comment by GrahamCampbell** [comment]
Had some feedback from symfony. See https://github.com/symfony/symfony/issues/14086#issuecomment-122119620.

**Comment by GrahamCampbell** [comment]
Given L5.1 is LTS, the PHP 7 fixes will end up getting backported where reasonable back into 5.1.

**Comment by Codenator81** [comment]
Yes it make sense if Laravel5.1 is LTS and PHP 7 well RC in November

**Comment by GrahamCampbell** [comment]
Yeh, we indent to have all currently supported Laravel versions working on all currently supported PHP versions. This means L5.1 will be working on php 5.5, 5.6, 7.0 before php 7 goes stable.

**Comment by nicolas-grekas** [comment]
In Symfony, we cast Throwables to FatalThrowableError:
```php
        if (!$exception instanceof \Exception) {
            $exception = new FatalThrowableError($exception);
        }
```
Laravel should do the same don't you think?

**Comment by GrahamCampbell** [comment]
That works for me. :)

**Comment by GrahamCampbell** [comment]
We're planning on getting 5.2 fully working on php 7, then we're going to backport what's reasonable to 5.1 after we've had time to test it for a bit.

**Comment by GrahamCampbell** [comment]
Ok, we've got this sorted. PHP 7 support should ship in the next 5.1 release.

**Comment by Codenator81** [comment]
Great. )

**Comment by TheShiftExchange** [comment]
@GrahamCampbell - I just got this error on Laravel 5.1.26 (LTS) running on Homestead PHP7.0.0RC5

To replicate - I was accidentally injecting a FormRequest object on one of my controller methods during a GET request (which I know I shouldnt - it was an accident).

It keep throwing me  the exact error above - which made it difficult to determine what was going on.

So it seems the issue is not fully fixed yet?

**Comment by GrahamCampbell** [comment]
This issue should have been fixed in 5.1+. I fixed it myself.

**Comment by TheShiftExchange** [comment]
Well - I'm running 5.1.26 and I got the error above - so it can still occur...

**Comment by TheShiftExchange** [comment]
Actually - its a slightly different error:

```
Type error: Argument 1 passed to Symfony\Component\Debug\Exception\FlattenException::create() must be an instance of Exception, instance of ParseError given
```

And to cause it - I had a syntax error in my PHP code - but I couldnt work it out for ages (because the error message wasnt helpful). In my FormRequest object I had this:

```
        return [
            'date' => 'required|string|date_format:d-m-Y'
            'area_list' => 'required|string|exists:area_staff_sheet_lists,id'
            'shift_type' => 'required|string|in:day,night,oncall'
        ];
```

Notice the missing 'commas' at the end of each row

**Comment by TheShiftExchange** [comment]
I've opened a seperate ticket for it - 11329

**Comment by missael** [comment]
[Symfony\Component\Debug\Exception\FatalErrorException]                                                                                           
  Uncaught TypeError: Argument 1 passed to App\Exceptions\Handler::report() must be an instance of Exception, instance of Error given, called in /  
  var/www/laravel/cmve/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 73 and defined in /var/www/larave  
  l/cmve/app/Exceptions/Handler.php:25                                                                                                              
  Stack trace:                                                                                                                                      
  #0 /var/www/laravel/cmve/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(73): App\Exceptions\Handler->report(O  
  bject(Error))                                                                                                                                     
  #1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Error))                                          
  #2 {main}                                                                                                                                         
    thrown

**Comment by adulion** [comment]
@missael did you get this sorted? i have exactly the same issue
